"""mig 2

Revision ID: 719334dc6b15
Revises: bfe43ce3a43f
Create Date: 2024-07-23 21:00:47.207581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719334dc6b15'
down_revision: Union[str, None] = 'bfe43ce3a43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detective', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_name", ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detective', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
