"""mig 2

Revision ID: c88bd82ebfd6
Revises: e0e851ab1bd3
Create Date: 2024-07-22 21:51:47.585381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88bd82ebfd6'
down_revision: Union[str, None] = 'e0e851ab1bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detective_clue_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detective_id', sa.Integer(), nullable=True),
    sa.Column('clue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clue_id'], ['clue.id'], ),
    sa.ForeignKeyConstraint(['detective_id'], ['detective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('detective', 'latest_puzzle_number_solved')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detective', sa.Column('latest_puzzle_number_solved', sa.INTEGER(), nullable=True))
    op.drop_table('detective_clue_link')
    # ### end Alembic commands ###
