"""Initial migration

Revision ID: e0e851ab1bd3
Revises: 
Create Date: 2024-07-22 00:47:24.119029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e851ab1bd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('released', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('detective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latest_puzzle_number_solved', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detective_id', sa.Integer(), nullable=True),
    sa.Column('clue_id', sa.Integer(), nullable=True),
    sa.Column('suspect', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clue_id'], ['clue.id'], ),
    sa.ForeignKeyConstraint(['detective_id'], ['detective.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clue_id', 'detective_id', name='__clue_id_detective_id_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('detective')
    op.drop_table('clue')
    # ### end Alembic commands ###
